Add remove item
thecodechaser/todo-list pull request #4
Opened 2021-12-03 13:23 UTC by thecodechaser

This branch includes the following features:
Added functionality to add items to the to-do list.
Added functionality to remove items to the to-do list.
Users can check the tasks that are completed.
Users can delete all the completed tasks at once.
Users can update the values of tasks.
Delete option shows up on the screen when user mark task as completed.

2021-12-03 14:45 UTC, mikenath223 requested changes
Hello @thecodechaser 

You've done pretty well so far!
But for a few issues, you are almost done with this. Hang in there!


## Required Changes ♻️
_Please check the comments under the review._


Happy coding, Cheers! 🚀🚀

Do feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether it is valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-03 14:46 UTC, mikenath223 commented on src/utils/interaction.js
> +/* eslint-disable import/no-cycle */
- [ ] Kindly remove this eslint disable line its best to fix the issue in the code.

2021-12-03 14:47 UTC, mikenath223 commented on src/utils/interaction.js
> +function userInteraction(listInput) {
- [ ] Please change this and all other regular functions into arrow functions, following the Javascript best practices guide.

2021-12-03 14:47 UTC, mikenath223 commented on src/utils/structure.js
> +/* eslint-disable no-use-before-define */
- [ ] Kindly remove this eslint disable line its best to fix the issue in the code.

2021-12-03 21:18 UTC, D4nielJ requested changes
## Hello @thecodechaser, 

Great work on making the changes requested by the previous reviewer(s) 👏

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Happy coding and stay awesome! 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-03 21:18 UTC, D4nielJ commented on src/utils/structure.js
> +};
- [ ] It seems like the "Clear all completed" functionality it's not working properly. When I click on the button the tasks that are marked as completed remain in the list.

> A function for the "Clear all completed" button using the `Array.filter()` method is implemented.

![todo-list](https://user-images.githubusercontent.com/79114233/144674014-8d27d246-59ba-4fa3-b690-f699d275edb0.gif)

2021-12-04 09:54 UTC, mikenath223 approved these changes
Hello there  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🛳 
Congratulations! 🎉 

Happy coding. Cheers! 🚀🚀

If you feel something isn't clear enough you can leave a question or comment in the PR thread.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-04 11:03 UTC, merged